// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
)

const appendDeploymentLog = `-- name: AppendDeploymentLog :exec
UPDATE deployments SET
    logs = logs || ?,
    status = ?,
    steps = ?
WHERE id = ?
`

type AppendDeploymentLogParams struct {
	Logs   string `json:"logs"`
	Status string `json:"status"`
	Steps  string `json:"steps"`
	ID     string `json:"id"`
}

func (q *Queries) AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) error {
	_, err := q.db.ExecContext(ctx, appendDeploymentLog,
		arg.Logs,
		arg.Status,
		arg.Steps,
		arg.ID,
	)
	return err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    id, service_id, commit_hash, commit_message, branch, author, status, steps, logs
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, service_id, commit_hash, commit_message, branch, author, status, steps, logs, duration_ms, started_at, finished_at, created_at
`

type CreateDeploymentParams struct {
	ID            string `json:"id"`
	ServiceID     string `json:"service_id"`
	CommitHash    string `json:"commit_hash"`
	CommitMessage string `json:"commit_message"`
	Branch        string `json:"branch"`
	Author        string `json:"author"`
	Status        string `json:"status"`
	Steps         string `json:"steps"`
	Logs          string `json:"logs"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.ServiceID,
		arg.CommitHash,
		arg.CommitMessage,
		arg.Branch,
		arg.Author,
		arg.Status,
		arg.Steps,
		arg.Logs,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.Branch,
		&i.Author,
		&i.Status,
		&i.Steps,
		&i.Logs,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, service_id, commit_hash, commit_message, branch, author, status, steps, logs, duration_ms, started_at, finished_at, created_at FROM deployments WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.Branch,
		&i.Author,
		&i.Status,
		&i.Steps,
		&i.Logs,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentsByService = `-- name: ListDeploymentsByService :many
SELECT id, service_id, commit_hash, commit_message, branch, author, status, steps, logs, duration_ms, started_at, finished_at, created_at FROM deployments WHERE service_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByService(ctx context.Context, serviceID string) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.CommitHash,
			&i.CommitMessage,
			&i.Branch,
			&i.Author,
			&i.Status,
			&i.Steps,
			&i.Logs,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments SET
    status = ?,
    duration_ms = ?,
    finished_at = ?,
    steps = ?,
    logs = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status     string       `json:"status"`
	DurationMs int64        `json:"duration_ms"`
	FinishedAt sql.NullTime `json:"finished_at"`
	Steps      string       `json:"steps"`
	Logs       string       `json:"logs"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus,
		arg.Status,
		arg.DurationMs,
		arg.FinishedAt,
		arg.Steps,
		arg.Logs,
		arg.ID,
	)
	return err
}
