// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const appendDeploymentLog = `-- name: AppendDeploymentLog :exec
UPDATE deployments SET
    logs = logs || ?,
    status = ?,
    steps = ?
WHERE id = ?
`

type AppendDeploymentLogParams struct {
	Logs   string `json:"logs"`
	Status string `json:"status"`
	Steps  string `json:"steps"`
	ID     string `json:"id"`
}

func (q *Queries) AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) error {
	_, err := q.db.ExecContext(ctx, appendDeploymentLog,
		arg.Logs,
		arg.Status,
		arg.Steps,
		arg.ID,
	)
	return err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
    id, service_id, commit_hash, commit_message, branch, author, status, steps, logs, url
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, service_id, commit_hash, commit_message, branch, author, status, steps, logs, duration_ms, started_at, finished_at, created_at, url
`

type CreateDeploymentParams struct {
	ID            string `json:"id"`
	ServiceID     string `json:"service_id"`
	CommitHash    string `json:"commit_hash"`
	CommitMessage string `json:"commit_message"`
	Branch        string `json:"branch"`
	Author        string `json:"author"`
	Status        string `json:"status"`
	Steps         string `json:"steps"`
	Logs          string `json:"logs"`
	Url           string `json:"url"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.ServiceID,
		arg.CommitHash,
		arg.CommitMessage,
		arg.Branch,
		arg.Author,
		arg.Status,
		arg.Steps,
		arg.Logs,
		arg.Url,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.Branch,
		&i.Author,
		&i.Status,
		&i.Steps,
		&i.Logs,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Url,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, service_id, commit_hash, commit_message, branch, author, status, steps, logs, duration_ms, started_at, finished_at, created_at, url FROM deployments WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.CommitHash,
		&i.CommitMessage,
		&i.Branch,
		&i.Author,
		&i.Status,
		&i.Steps,
		&i.Logs,
		&i.DurationMs,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.Url,
	)
	return i, err
}

const listDeploymentsByService = `-- name: ListDeploymentsByService :many
SELECT id, service_id, commit_hash, commit_message, branch, author, status, steps, logs, duration_ms, started_at, finished_at, created_at, url FROM deployments WHERE service_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsByService(ctx context.Context, serviceID string) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.CommitHash,
			&i.CommitMessage,
			&i.Branch,
			&i.Author,
			&i.Status,
			&i.Steps,
			&i.Logs,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsWithServiceByService = `-- name: ListDeploymentsWithServiceByService :many
SELECT 
    d.id, d.service_id, COALESCE(s.name, 'Service') as service_name,
    d.commit_hash, d.commit_message, d.branch, d.author,
    d.status, d.steps, d.logs, d.duration_ms, d.started_at,
    d.finished_at, d.created_at, d.url
FROM deployments d
LEFT JOIN services s ON d.service_id = s.id
WHERE d.service_id = ?
ORDER BY d.created_at DESC
`

type ListDeploymentsWithServiceByServiceRow struct {
	ID            string       `json:"id"`
	ServiceID     string       `json:"service_id"`
	ServiceName   string       `json:"service_name"`
	CommitHash    string       `json:"commit_hash"`
	CommitMessage string       `json:"commit_message"`
	Branch        string       `json:"branch"`
	Author        string       `json:"author"`
	Status        string       `json:"status"`
	Steps         string       `json:"steps"`
	Logs          string       `json:"logs"`
	DurationMs    int64        `json:"duration_ms"`
	StartedAt     time.Time    `json:"started_at"`
	FinishedAt    sql.NullTime `json:"finished_at"`
	CreatedAt     time.Time    `json:"created_at"`
	Url           string       `json:"url"`
}

func (q *Queries) ListDeploymentsWithServiceByService(ctx context.Context, serviceID string) ([]ListDeploymentsWithServiceByServiceRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentsWithServiceByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeploymentsWithServiceByServiceRow{}
	for rows.Next() {
		var i ListDeploymentsWithServiceByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.ServiceName,
			&i.CommitHash,
			&i.CommitMessage,
			&i.Branch,
			&i.Author,
			&i.Status,
			&i.Steps,
			&i.Logs,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeployments = `-- name: ListRecentDeployments :many
SELECT 
    d.id, d.service_id, COALESCE(s.name, 'Service') as service_name,
    d.commit_hash, d.commit_message, d.branch, d.author,
    d.status, d.steps, d.logs, d.duration_ms, d.started_at,
    d.finished_at, d.created_at, d.url
FROM deployments d
LEFT JOIN services s ON d.service_id = s.id
ORDER BY d.created_at DESC
LIMIT ?
`

type ListRecentDeploymentsRow struct {
	ID            string       `json:"id"`
	ServiceID     string       `json:"service_id"`
	ServiceName   string       `json:"service_name"`
	CommitHash    string       `json:"commit_hash"`
	CommitMessage string       `json:"commit_message"`
	Branch        string       `json:"branch"`
	Author        string       `json:"author"`
	Status        string       `json:"status"`
	Steps         string       `json:"steps"`
	Logs          string       `json:"logs"`
	DurationMs    int64        `json:"duration_ms"`
	StartedAt     time.Time    `json:"started_at"`
	FinishedAt    sql.NullTime `json:"finished_at"`
	CreatedAt     time.Time    `json:"created_at"`
	Url           string       `json:"url"`
}

func (q *Queries) ListRecentDeployments(ctx context.Context, limit int64) ([]ListRecentDeploymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeployments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentDeploymentsRow{}
	for rows.Next() {
		var i ListRecentDeploymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.ServiceName,
			&i.CommitHash,
			&i.CommitMessage,
			&i.Branch,
			&i.Author,
			&i.Status,
			&i.Steps,
			&i.Logs,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments SET
    status = ?,
    duration_ms = ?,
    finished_at = ?,
    steps = ?,
    logs = ?,
    url = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status     string       `json:"status"`
	DurationMs int64        `json:"duration_ms"`
	FinishedAt sql.NullTime `json:"finished_at"`
	Steps      string       `json:"steps"`
	Logs       string       `json:"logs"`
	Url        string       `json:"url"`
	ID         string       `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus,
		arg.Status,
		arg.DurationMs,
		arg.FinishedAt,
		arg.Steps,
		arg.Logs,
		arg.Url,
		arg.ID,
	)
	return err
}
