// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listClusterMetrics = `-- name: ListClusterMetrics :many
SELECT 
    recorded_at,
    AVG(cpu_percent) as avg_cpu_percent,
    SUM(memory_used_mb) as total_memory_used_mb,
    SUM(memory_total_mb) as total_memory_total_mb,
    SUM(disk_used_gb) as total_disk_used_gb,
    SUM(disk_total_gb) as total_disk_total_gb,
    SUM(network_rx_kbps) as total_network_rx_kbps,
    SUM(network_tx_kbps) as total_network_tx_kbps
FROM node_metrics
WHERE recorded_at >= datetime('now', ? || ' seconds')
GROUP BY strftime('%Y-%m-%d %H:%M', recorded_at)
ORDER BY recorded_at ASC
`

type ListClusterMetricsRow struct {
	RecordedAt         time.Time       `json:"recorded_at"`
	AvgCpuPercent      sql.NullFloat64 `json:"avg_cpu_percent"`
	TotalMemoryUsedMb  sql.NullFloat64 `json:"total_memory_used_mb"`
	TotalMemoryTotalMb sql.NullFloat64 `json:"total_memory_total_mb"`
	TotalDiskUsedGb    sql.NullFloat64 `json:"total_disk_used_gb"`
	TotalDiskTotalGb   sql.NullFloat64 `json:"total_disk_total_gb"`
	TotalNetworkRxKbps sql.NullFloat64 `json:"total_network_rx_kbps"`
	TotalNetworkTxKbps sql.NullFloat64 `json:"total_network_tx_kbps"`
}

func (q *Queries) ListClusterMetrics(ctx context.Context, dollar_1 sql.NullString) ([]ListClusterMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClusterMetrics, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClusterMetricsRow{}
	for rows.Next() {
		var i ListClusterMetricsRow
		if err := rows.Scan(
			&i.RecordedAt,
			&i.AvgCpuPercent,
			&i.TotalMemoryUsedMb,
			&i.TotalMemoryTotalMb,
			&i.TotalDiskUsedGb,
			&i.TotalDiskTotalGb,
			&i.TotalNetworkRxKbps,
			&i.TotalNetworkTxKbps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeMetrics = `-- name: ListNodeMetrics :many
SELECT id, node_id, cpu_percent, memory_used_mb, memory_total_mb, disk_used_gb, disk_total_gb, network_rx_kbps, network_tx_kbps, recorded_at FROM node_metrics
WHERE node_id = ? AND recorded_at >= datetime('now', ? || ' seconds')
ORDER BY recorded_at ASC
`

type ListNodeMetricsParams struct {
	NodeID  string         `json:"node_id"`
	Column2 sql.NullString `json:"column_2"`
}

func (q *Queries) ListNodeMetrics(ctx context.Context, arg ListNodeMetricsParams) ([]NodeMetric, error) {
	rows, err := q.db.QueryContext(ctx, listNodeMetrics, arg.NodeID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeMetric{}
	for rows.Next() {
		var i NodeMetric
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.CpuPercent,
			&i.MemoryUsedMb,
			&i.MemoryTotalMb,
			&i.DiskUsedGb,
			&i.DiskTotalGb,
			&i.NetworkRxKbps,
			&i.NetworkTxKbps,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentNodeMetrics = `-- name: ListRecentNodeMetrics :many
SELECT id, node_id, cpu_percent, memory_used_mb, memory_total_mb, disk_used_gb, disk_total_gb, network_rx_kbps, network_tx_kbps, recorded_at FROM node_metrics
WHERE node_id = ?
ORDER BY recorded_at DESC
LIMIT ?
`

type ListRecentNodeMetricsParams struct {
	NodeID string `json:"node_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListRecentNodeMetrics(ctx context.Context, arg ListRecentNodeMetricsParams) ([]NodeMetric, error) {
	rows, err := q.db.QueryContext(ctx, listRecentNodeMetrics, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeMetric{}
	for rows.Next() {
		var i NodeMetric
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.CpuPercent,
			&i.MemoryUsedMb,
			&i.MemoryTotalMb,
			&i.DiskUsedGb,
			&i.DiskTotalGb,
			&i.NetworkRxKbps,
			&i.NetworkTxKbps,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordNodeMetric = `-- name: RecordNodeMetric :one
INSERT INTO node_metrics (
    node_id, cpu_percent, memory_used_mb, memory_total_mb, disk_used_gb, disk_total_gb, network_rx_kbps, network_tx_kbps
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, node_id, cpu_percent, memory_used_mb, memory_total_mb, disk_used_gb, disk_total_gb, network_rx_kbps, network_tx_kbps, recorded_at
`

type RecordNodeMetricParams struct {
	NodeID        string  `json:"node_id"`
	CpuPercent    float64 `json:"cpu_percent"`
	MemoryUsedMb  int64   `json:"memory_used_mb"`
	MemoryTotalMb int64   `json:"memory_total_mb"`
	DiskUsedGb    int64   `json:"disk_used_gb"`
	DiskTotalGb   int64   `json:"disk_total_gb"`
	NetworkRxKbps float64 `json:"network_rx_kbps"`
	NetworkTxKbps float64 `json:"network_tx_kbps"`
}

func (q *Queries) RecordNodeMetric(ctx context.Context, arg RecordNodeMetricParams) (NodeMetric, error) {
	row := q.db.QueryRowContext(ctx, recordNodeMetric,
		arg.NodeID,
		arg.CpuPercent,
		arg.MemoryUsedMb,
		arg.MemoryTotalMb,
		arg.DiskUsedGb,
		arg.DiskTotalGb,
		arg.NetworkRxKbps,
		arg.NetworkTxKbps,
	)
	var i NodeMetric
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.CpuPercent,
		&i.MemoryUsedMb,
		&i.MemoryTotalMb,
		&i.DiskUsedGb,
		&i.DiskTotalGb,
		&i.NetworkRxKbps,
		&i.NetworkTxKbps,
		&i.RecordedAt,
	)
	return i, err
}
