// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"
	"database/sql"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
    id, name, ip_address, public_ip, role, status,
    cpu_total_cores, memory_total_mb, disk_total_gb,
    docker_version, os, kernel_version, enroll_token
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?
) RETURNING id, name, ip_address, public_ip, role, status, cpu_total_cores, memory_total_mb, disk_total_gb, cpu_percent, memory_used_mb, disk_used_gb, network_rx_kbps, network_tx_kbps, docker_version, os, kernel_version, uptime, last_heartbeat, enroll_token, created_at, updated_at
`

type CreateNodeParams struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	IpAddress     string  `json:"ip_address"`
	PublicIp      string  `json:"public_ip"`
	Role          string  `json:"role"`
	Status        string  `json:"status"`
	CpuTotalCores int64   `json:"cpu_total_cores"`
	MemoryTotalMb int64   `json:"memory_total_mb"`
	DiskTotalGb   float64 `json:"disk_total_gb"`
	DockerVersion string  `json:"docker_version"`
	Os            string  `json:"os"`
	KernelVersion string  `json:"kernel_version"`
	EnrollToken   string  `json:"enroll_token"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.IpAddress,
		arg.PublicIp,
		arg.Role,
		arg.Status,
		arg.CpuTotalCores,
		arg.MemoryTotalMb,
		arg.DiskTotalGb,
		arg.DockerVersion,
		arg.Os,
		arg.KernelVersion,
		arg.EnrollToken,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IpAddress,
		&i.PublicIp,
		&i.Role,
		&i.Status,
		&i.CpuTotalCores,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuPercent,
		&i.MemoryUsedMb,
		&i.DiskUsedGb,
		&i.NetworkRxKbps,
		&i.NetworkTxKbps,
		&i.DockerVersion,
		&i.Os,
		&i.KernelVersion,
		&i.Uptime,
		&i.LastHeartbeat,
		&i.EnrollToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, ip_address, public_ip, role, status, cpu_total_cores, memory_total_mb, disk_total_gb, cpu_percent, memory_used_mb, disk_used_gb, network_rx_kbps, network_tx_kbps, docker_version, os, kernel_version, uptime, last_heartbeat, enroll_token, created_at, updated_at FROM nodes WHERE id = ? LIMIT 1
`

func (q *Queries) GetNodeByID(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IpAddress,
		&i.PublicIp,
		&i.Role,
		&i.Status,
		&i.CpuTotalCores,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuPercent,
		&i.MemoryUsedMb,
		&i.DiskUsedGb,
		&i.NetworkRxKbps,
		&i.NetworkTxKbps,
		&i.DockerVersion,
		&i.Os,
		&i.KernelVersion,
		&i.Uptime,
		&i.LastHeartbeat,
		&i.EnrollToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, ip_address, public_ip, role, status, cpu_total_cores, memory_total_mb, disk_total_gb, cpu_percent, memory_used_mb, disk_used_gb, network_rx_kbps, network_tx_kbps, docker_version, os, kernel_version, uptime, last_heartbeat, enroll_token, created_at, updated_at FROM nodes ORDER BY created_at DESC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IpAddress,
			&i.PublicIp,
			&i.Role,
			&i.Status,
			&i.CpuTotalCores,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuPercent,
			&i.MemoryUsedMb,
			&i.DiskUsedGb,
			&i.NetworkRxKbps,
			&i.NetworkTxKbps,
			&i.DockerVersion,
			&i.Os,
			&i.KernelVersion,
			&i.Uptime,
			&i.LastHeartbeat,
			&i.EnrollToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInactiveNodesOffline = `-- name: MarkInactiveNodesOffline :many
UPDATE nodes SET
    status = 'offline',
    updated_at = CURRENT_TIMESTAMP
WHERE status = 'online'
  AND (last_heartbeat IS NULL OR datetime(last_heartbeat, ? || ' seconds') < CURRENT_TIMESTAMP)
RETURNING id, name
`

type MarkInactiveNodesOfflineRow struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) MarkInactiveNodesOffline(ctx context.Context, dollar_1 sql.NullString) ([]MarkInactiveNodesOfflineRow, error) {
	rows, err := q.db.QueryContext(ctx, markInactiveNodesOffline, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarkInactiveNodesOfflineRow{}
	for rows.Next() {
		var i MarkInactiveNodesOfflineRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :exec
UPDATE nodes SET
    status = ?,
    cpu_percent = ?,
    memory_used_mb = ?,
    disk_used_gb = ?,
    network_rx_kbps = ?,
    network_tx_kbps = ?,
    uptime = ?,
    last_heartbeat = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNodeHeartbeatParams struct {
	Status        string  `json:"status"`
	CpuPercent    float64 `json:"cpu_percent"`
	MemoryUsedMb  int64   `json:"memory_used_mb"`
	DiskUsedGb    float64 `json:"disk_used_gb"`
	NetworkRxKbps float64 `json:"network_rx_kbps"`
	NetworkTxKbps float64 `json:"network_tx_kbps"`
	Uptime        string  `json:"uptime"`
	ID            string  `json:"id"`
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeHeartbeat,
		arg.Status,
		arg.CpuPercent,
		arg.MemoryUsedMb,
		arg.DiskUsedGb,
		arg.NetworkRxKbps,
		arg.NetworkTxKbps,
		arg.Uptime,
		arg.ID,
	)
	return err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :exec
UPDATE nodes SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateNodeStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNodeStatus, arg.Status, arg.ID)
	return err
}
