// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateServiceDomain(ctx context.Context, arg CreateServiceDomainParams) (ServiceDomain, error)
	CreateServiceEnvVar(ctx context.Context, arg CreateServiceEnvVarParams) (ServiceEnvVar, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNode(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
	DeleteService(ctx context.Context, id string) error
	DeleteServiceDomains(ctx context.Context, serviceID string) error
	DeleteServiceEnvVars(ctx context.Context, serviceID string) error
	DeleteSetting(ctx context.Context, key string) error
	GetDeploymentByID(ctx context.Context, id string) (Deployment, error)
	GetNodeByID(ctx context.Context, id string) (Node, error)
	GetProjectByID(ctx context.Context, id string) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetServiceByID(ctx context.Context, id string) (Service, error)
	GetSetting(ctx context.Context, key string) (ClusterSetting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListAllServices(ctx context.Context) ([]Service, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListDeploymentsByService(ctx context.Context, serviceID string) ([]Deployment, error)
	ListNodeMetrics(ctx context.Context, arg ListNodeMetricsParams) ([]NodeMetric, error)
	ListNodes(ctx context.Context) ([]Node, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListRecentNodeMetrics(ctx context.Context, arg ListRecentNodeMetricsParams) ([]NodeMetric, error)
	ListServiceDomains(ctx context.Context, serviceID string) ([]ServiceDomain, error)
	ListServiceEnvVars(ctx context.Context, serviceID string) ([]ServiceEnvVar, error)
	ListServicesByNode(ctx context.Context, nodeID string) ([]Service, error)
	ListServicesByProject(ctx context.Context, projectID string) ([]Service, error)
	ListSettings(ctx context.Context) ([]ClusterSetting, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MarkInactiveNodesOffline(ctx context.Context, dollar_1 sql.NullString) ([]MarkInactiveNodesOfflineRow, error)
	RecordNodeMetric(ctx context.Context, arg RecordNodeMetricParams) (NodeMetric, error)
	SetSetting(ctx context.Context, arg SetSettingParams) (ClusterSetting, error)
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error
	UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error
	UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error
	UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
