// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    id, project_id, node_id, name, slug, type, status,
    repository, branch, commit_hash, dockerfile, build_command,
    compose_file, image, database_type, database_version,
    connection_string, ports, replicas, cpu_limit, memory_limit_mb
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?
) RETURNING id, project_id, node_id, name, slug, type, status, repository, branch, commit_hash, dockerfile, build_command, compose_file, image, database_type, database_version, connection_string, ports, replicas, cpu_limit, memory_limit_mb, created_at, updated_at
`

type CreateServiceParams struct {
	ID               string  `json:"id"`
	ProjectID        string  `json:"project_id"`
	NodeID           string  `json:"node_id"`
	Name             string  `json:"name"`
	Slug             string  `json:"slug"`
	Type             string  `json:"type"`
	Status           string  `json:"status"`
	Repository       string  `json:"repository"`
	Branch           string  `json:"branch"`
	CommitHash       string  `json:"commit_hash"`
	Dockerfile       string  `json:"dockerfile"`
	BuildCommand     string  `json:"build_command"`
	ComposeFile      string  `json:"compose_file"`
	Image            string  `json:"image"`
	DatabaseType     string  `json:"database_type"`
	DatabaseVersion  string  `json:"database_version"`
	ConnectionString string  `json:"connection_string"`
	Ports            string  `json:"ports"`
	Replicas         int64   `json:"replicas"`
	CpuLimit         float64 `json:"cpu_limit"`
	MemoryLimitMb    int64   `json:"memory_limit_mb"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.ID,
		arg.ProjectID,
		arg.NodeID,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.Status,
		arg.Repository,
		arg.Branch,
		arg.CommitHash,
		arg.Dockerfile,
		arg.BuildCommand,
		arg.ComposeFile,
		arg.Image,
		arg.DatabaseType,
		arg.DatabaseVersion,
		arg.ConnectionString,
		arg.Ports,
		arg.Replicas,
		arg.CpuLimit,
		arg.MemoryLimitMb,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NodeID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Status,
		&i.Repository,
		&i.Branch,
		&i.CommitHash,
		&i.Dockerfile,
		&i.BuildCommand,
		&i.ComposeFile,
		&i.Image,
		&i.DatabaseType,
		&i.DatabaseVersion,
		&i.ConnectionString,
		&i.Ports,
		&i.Replicas,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceDomain = `-- name: CreateServiceDomain :one
INSERT INTO service_domains (
    id, service_id, domain, ssl, is_primary, port, path, certificate_type
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, service_id, domain, ssl, is_primary, port, path, certificate_type, created_at
`

type CreateServiceDomainParams struct {
	ID              string `json:"id"`
	ServiceID       string `json:"service_id"`
	Domain          string `json:"domain"`
	Ssl             int64  `json:"ssl"`
	IsPrimary       int64  `json:"is_primary"`
	Port            int64  `json:"port"`
	Path            string `json:"path"`
	CertificateType string `json:"certificate_type"`
}

func (q *Queries) CreateServiceDomain(ctx context.Context, arg CreateServiceDomainParams) (ServiceDomain, error) {
	row := q.db.QueryRowContext(ctx, createServiceDomain,
		arg.ID,
		arg.ServiceID,
		arg.Domain,
		arg.Ssl,
		arg.IsPrimary,
		arg.Port,
		arg.Path,
		arg.CertificateType,
	)
	var i ServiceDomain
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Domain,
		&i.Ssl,
		&i.IsPrimary,
		&i.Port,
		&i.Path,
		&i.CertificateType,
		&i.CreatedAt,
	)
	return i, err
}

const createServiceEnvVar = `-- name: CreateServiceEnvVar :one
INSERT INTO service_env_vars (
    id, service_id, key, value, is_secret
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, service_id, "key", value, is_secret, created_at, updated_at
`

type CreateServiceEnvVarParams struct {
	ID        string `json:"id"`
	ServiceID string `json:"service_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	IsSecret  int64  `json:"is_secret"`
}

func (q *Queries) CreateServiceEnvVar(ctx context.Context, arg CreateServiceEnvVarParams) (ServiceEnvVar, error) {
	row := q.db.QueryRowContext(ctx, createServiceEnvVar,
		arg.ID,
		arg.ServiceID,
		arg.Key,
		arg.Value,
		arg.IsSecret,
	)
	var i ServiceEnvVar
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Key,
		&i.Value,
		&i.IsSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = ?
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const deleteServiceDomains = `-- name: DeleteServiceDomains :exec
DELETE FROM service_domains WHERE service_id = ?
`

func (q *Queries) DeleteServiceDomains(ctx context.Context, serviceID string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceDomains, serviceID)
	return err
}

const deleteServiceEnvVars = `-- name: DeleteServiceEnvVars :exec
DELETE FROM service_env_vars WHERE service_id = ?
`

func (q *Queries) DeleteServiceEnvVars(ctx context.Context, serviceID string) error {
	_, err := q.db.ExecContext(ctx, deleteServiceEnvVars, serviceID)
	return err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, project_id, node_id, name, slug, type, status, repository, branch, commit_hash, dockerfile, build_command, compose_file, image, database_type, database_version, connection_string, ports, replicas, cpu_limit, memory_limit_mb, created_at, updated_at FROM services WHERE id = ? LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NodeID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Status,
		&i.Repository,
		&i.Branch,
		&i.CommitHash,
		&i.Dockerfile,
		&i.BuildCommand,
		&i.ComposeFile,
		&i.Image,
		&i.DatabaseType,
		&i.DatabaseVersion,
		&i.ConnectionString,
		&i.Ports,
		&i.Replicas,
		&i.CpuLimit,
		&i.MemoryLimitMb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, project_id, node_id, name, slug, type, status, repository, branch, commit_hash, dockerfile, build_command, compose_file, image, database_type, database_version, connection_string, ports, replicas, cpu_limit, memory_limit_mb, created_at, updated_at FROM services ORDER BY created_at DESC
`

func (q *Queries) ListAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NodeID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Status,
			&i.Repository,
			&i.Branch,
			&i.CommitHash,
			&i.Dockerfile,
			&i.BuildCommand,
			&i.ComposeFile,
			&i.Image,
			&i.DatabaseType,
			&i.DatabaseVersion,
			&i.ConnectionString,
			&i.Ports,
			&i.Replicas,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceDomains = `-- name: ListServiceDomains :many
SELECT id, service_id, domain, ssl, is_primary, port, path, certificate_type, created_at FROM service_domains WHERE service_id = ?
`

func (q *Queries) ListServiceDomains(ctx context.Context, serviceID string) ([]ServiceDomain, error) {
	rows, err := q.db.QueryContext(ctx, listServiceDomains, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceDomain{}
	for rows.Next() {
		var i ServiceDomain
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Domain,
			&i.Ssl,
			&i.IsPrimary,
			&i.Port,
			&i.Path,
			&i.CertificateType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceEnvVars = `-- name: ListServiceEnvVars :many
SELECT id, service_id, "key", value, is_secret, created_at, updated_at FROM service_env_vars WHERE service_id = ?
`

func (q *Queries) ListServiceEnvVars(ctx context.Context, serviceID string) ([]ServiceEnvVar, error) {
	rows, err := q.db.QueryContext(ctx, listServiceEnvVars, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceEnvVar{}
	for rows.Next() {
		var i ServiceEnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Key,
			&i.Value,
			&i.IsSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByNode = `-- name: ListServicesByNode :many
SELECT id, project_id, node_id, name, slug, type, status, repository, branch, commit_hash, dockerfile, build_command, compose_file, image, database_type, database_version, connection_string, ports, replicas, cpu_limit, memory_limit_mb, created_at, updated_at FROM services WHERE node_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListServicesByNode(ctx context.Context, nodeID string) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NodeID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Status,
			&i.Repository,
			&i.Branch,
			&i.CommitHash,
			&i.Dockerfile,
			&i.BuildCommand,
			&i.ComposeFile,
			&i.Image,
			&i.DatabaseType,
			&i.DatabaseVersion,
			&i.ConnectionString,
			&i.Ports,
			&i.Replicas,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByProject = `-- name: ListServicesByProject :many
SELECT id, project_id, node_id, name, slug, type, status, repository, branch, commit_hash, dockerfile, build_command, compose_file, image, database_type, database_version, connection_string, ports, replicas, cpu_limit, memory_limit_mb, created_at, updated_at FROM services WHERE project_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListServicesByProject(ctx context.Context, projectID string) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServicesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NodeID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Status,
			&i.Repository,
			&i.Branch,
			&i.CommitHash,
			&i.Dockerfile,
			&i.BuildCommand,
			&i.ComposeFile,
			&i.Image,
			&i.DatabaseType,
			&i.DatabaseVersion,
			&i.ConnectionString,
			&i.Ports,
			&i.Replicas,
			&i.CpuLimit,
			&i.MemoryLimitMb,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceStatus = `-- name: UpdateServiceStatus :exec
UPDATE services SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateServiceStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateServiceStatus(ctx context.Context, arg UpdateServiceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateServiceStatus, arg.Status, arg.ID)
	return err
}
