// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM cluster_settings WHERE key = ?
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT "key", value, updated_at FROM cluster_settings WHERE key = ? LIMIT 1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (ClusterSetting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var i ClusterSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT "key", value, updated_at FROM cluster_settings ORDER BY key ASC
`

func (q *Queries) ListSettings(ctx context.Context) ([]ClusterSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClusterSetting{}
	for rows.Next() {
		var i ClusterSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSetting = `-- name: SetSetting :one
INSERT INTO cluster_settings (
    key, value, updated_at
) VALUES (
    ?, ?, CURRENT_TIMESTAMP
)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
RETURNING "key", value, updated_at
`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) (ClusterSetting, error) {
	row := q.db.QueryRowContext(ctx, setSetting, arg.Key, arg.Value)
	var i ClusterSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
