package traefik

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteDynamicConfig generates and saves a Traefik v3 dynamic YAML routing file.
func WriteDynamicConfig(dir string, cfg RouteConfig) error {
	if dir == "" || len(cfg.Domains) == 0 || cfg.TargetPort <= 0 {
		return nil
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create dynamic config directory: %w", err)
	}

	name := sanitizeName(cfg.ServiceName)
	if name == "" {
		name = "app"
	}

	certResolver := cfg.CertResolver
	if certResolver == "" {
		certResolver = "letsencrypt"
	}

	var hostRules []string
	for _, d := range cfg.Domains {
		trimmed := strings.TrimSpace(d)
		if trimmed != "" {
			hostRules = append(hostRules, fmt.Sprintf("Host(`%s`)", trimmed))
		}
	}
	rule := strings.Join(hostRules, " || ")
	if cfg.PathPrefix != "" {
		rule = fmt.Sprintf("(%s) && PathPrefix(`%s`)", rule, cfg.PathPrefix)
	}

	// Dynamic YAML content
	var b strings.Builder
	b.WriteString("# Auto-generated by Tako Agent for " + cfg.ServiceName + "\n")
	b.WriteString("http:\n")
	b.WriteString("  routers:\n")

	if cfg.EnableTLS {
		// HTTPS router
		b.WriteString(fmt.Sprintf("    %s-secure:\n", name))
		b.WriteString(fmt.Sprintf("      rule: \"%s\"\n", rule))
		b.WriteString("      entryPoints:\n        - websecure\n")
		b.WriteString(fmt.Sprintf("      tls:\n        certResolver: %s\n", certResolver))
		b.WriteString(fmt.Sprintf("      service: %s\n", name))
		if len(cfg.Middlewares) > 0 {
			b.WriteString("      middlewares:\n")
			for _, m := range cfg.Middlewares {
				b.WriteString(fmt.Sprintf("        - %s\n", m))
			}
		}

		// HTTP redirect to HTTPS router
		b.WriteString(fmt.Sprintf("    %s-web:\n", name))
		b.WriteString(fmt.Sprintf("      rule: \"%s\"\n", rule))
		b.WriteString("      entryPoints:\n        - web\n")
		b.WriteString("      middlewares:\n")
		b.WriteString(fmt.Sprintf("        - %s-redirect-ssl\n", name))
		b.WriteString(fmt.Sprintf("      service: %s\n", name))

		// Middleware definition
		b.WriteString("  middlewares:\n")
		b.WriteString(fmt.Sprintf("    %s-redirect-ssl:\n", name))
		b.WriteString("      redirectScheme:\n        scheme: https\n        permanent: true\n")
	} else {
		// Plain HTTP router
		b.WriteString(fmt.Sprintf("    %s-web:\n", name))
		b.WriteString(fmt.Sprintf("      rule: \"%s\"\n", rule))
		b.WriteString("      entryPoints:\n        - web\n")
		b.WriteString(fmt.Sprintf("      service: %s\n", name))
		if len(cfg.Middlewares) > 0 {
			b.WriteString("      middlewares:\n")
			for _, m := range cfg.Middlewares {
				b.WriteString(fmt.Sprintf("        - %s\n", m))
			}
		}
	}

	// Service definition
	b.WriteString("  services:\n")
	b.WriteString(fmt.Sprintf("    %s:\n", name))
	b.WriteString("      loadBalancer:\n        servers:\n")
	b.WriteString(fmt.Sprintf("          - url: \"http://%s:%d\"\n", name, cfg.TargetPort))

	filePath := filepath.Join(dir, fmt.Sprintf("%s.yml", name))
	return os.WriteFile(filePath, []byte(b.String()), 0644)
}

// RemoveDynamicConfig deletes a service's dynamic YAML routing file.
func RemoveDynamicConfig(dir, serviceName string) error {
	if dir == "" || serviceName == "" {
		return nil
	}
	name := sanitizeName(serviceName)
	filePath := filepath.Join(dir, fmt.Sprintf("%s.yml", name))
	if err := os.Remove(filePath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
