package traefik

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteDynamicConfig generates and saves a Traefik v3 dynamic YAML routing file.
// - Production custom domains (cfg.EnableTLS=true): HTTPS router + HTTP→HTTPS redirect router.
// - Preview sslip.io domains (cfg.EnableTLS=false): plain HTTP router only.
// The backend URL always uses the actual Docker container hostname: tako-app-<serviceName>.
func WriteDynamicConfig(dir string, cfg RouteConfig) error {
	if dir == "" || len(cfg.Domains) == 0 || cfg.TargetPort <= 0 {
		return nil
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create dynamic config directory: %w", err)
	}

	name := sanitizeName(cfg.ServiceName)
	if name == "" {
		name = "app"
	}

	configName := name
	if cfg.ConfigName != "" {
		configName = sanitizeName(cfg.ConfigName)
	}

	certResolver := cfg.CertResolver
	if certResolver == "" {
		certResolver = "letsencrypt"
	}

	// Actual Docker container hostname is tako-app-<serviceName> (unless ContainerName is set)
	containerHost := cfg.ContainerName
	if containerHost == "" {
		containerHost = "tako-app-" + name
	}

	// Split domains into TLS-capable (custom) and preview (sslip.io / plain HTTP)
	var tlsDomains, httpDomains []string
	for _, d := range cfg.Domains {
		trimmed := strings.TrimSpace(d)
		if trimmed == "" {
			continue
		}
		if strings.HasSuffix(trimmed, ".sslip.io") || strings.HasSuffix(trimmed, ".nip.io") || strings.HasSuffix(trimmed, ".xip.io") {
			httpDomains = append(httpDomains, trimmed)
		} else {
			tlsDomains = append(tlsDomains, trimmed)
		}
	}

	// If EnableTLS is explicitly false, all domains go to HTTP
	if !cfg.EnableTLS {
		httpDomains = append(httpDomains, tlsDomains...)
		tlsDomains = nil
	}

	buildHostRule := func(domains []string) string {
		var parts []string
		for _, d := range domains {
			parts = append(parts, fmt.Sprintf("Host(`%s`)", d))
		}
		rule := strings.Join(parts, " || ")
		if cfg.PathPrefix != "" {
			rule = fmt.Sprintf("(%s) && PathPrefix(`%s`)", rule, cfg.PathPrefix)
		}
		return rule
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by Tako Agent for " + cfg.ServiceName + "\n")
	b.WriteString("http:\n")
	b.WriteString("  routers:\n")

	// TLS (HTTPS) routers for production custom domains
	if len(tlsDomains) > 0 {
		tlsRule := buildHostRule(tlsDomains)

		// HTTPS router
		b.WriteString(fmt.Sprintf("    %s-secure:\n", configName))
		b.WriteString(fmt.Sprintf("      rule: \"%s\"\n", tlsRule))
		b.WriteString("      entryPoints:\n        - websecure\n")
		b.WriteString(fmt.Sprintf("      tls:\n        certResolver: %s\n", certResolver))
		b.WriteString(fmt.Sprintf("      service: %s\n", configName))
		if len(cfg.Middlewares) > 0 {
			b.WriteString("      middlewares:\n")
			for _, m := range cfg.Middlewares {
				b.WriteString(fmt.Sprintf("        - %s\n", m))
			}
		}

		// HTTP→HTTPS redirect router for custom domains
		b.WriteString(fmt.Sprintf("    %s-web:\n", configName))
		b.WriteString(fmt.Sprintf("      rule: \"%s\"\n", tlsRule))
		b.WriteString("      entryPoints:\n        - web\n")
		b.WriteString(fmt.Sprintf("      middlewares:\n        - %s-redirect-ssl\n", configName))
		b.WriteString(fmt.Sprintf("      service: %s\n", configName))

		// Redirect middleware definition
		if _, err := b.WriteString("  middlewares:\n"); err == nil {
			b.WriteString(fmt.Sprintf("    %s-redirect-ssl:\n", configName))
			b.WriteString("      redirectScheme:\n        scheme: https\n        permanent: true\n")
		}
	}

	// Plain HTTP routers for sslip.io / nip.io preview domains
	if len(httpDomains) > 0 {
		httpRule := buildHostRule(httpDomains)

		b.WriteString(fmt.Sprintf("    %s-preview:\n", configName))
		b.WriteString(fmt.Sprintf("      rule: \"%s\"\n", httpRule))
		b.WriteString("      entryPoints:\n        - web\n")
		b.WriteString(fmt.Sprintf("      service: %s\n", configName))
		if len(cfg.Middlewares) > 0 {
			b.WriteString("      middlewares:\n")
			for _, m := range cfg.Middlewares {
				b.WriteString(fmt.Sprintf("        - %s\n", m))
			}
		}
	}

	// Service backend — MUST use the actual Docker container hostname
	b.WriteString("  services:\n")
	b.WriteString(fmt.Sprintf("    %s:\n", configName))
	b.WriteString("      loadBalancer:\n        servers:\n")
	b.WriteString(fmt.Sprintf("          - url: \"http://%s:%d\"\n", containerHost, cfg.TargetPort))

	filePath := filepath.Join(dir, fmt.Sprintf("%s.yml", configName))
	return os.WriteFile(filePath, []byte(b.String()), 0644)
}

// RemoveDynamicConfig deletes a service's dynamic YAML routing file.
func RemoveDynamicConfig(dir, serviceName string) error {
	if dir == "" || serviceName == "" {
		return nil
	}
	name := sanitizeName(serviceName)
	filePath := filepath.Join(dir, fmt.Sprintf("%s.yml", name))
	if err := os.Remove(filePath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
