global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: false
  insecure: false

ping:
  entryPoint: web

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TAKO_ACME_EMAIL:-admin@gettako.dev}
      storage: /acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "tako-network"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true
